version: "3.9"

volumes:
  githuber-sync:
    external: true

services:
  web:
    tty: true
    stdin_open: true
    build: .
    command: bash -c "bundle && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - githuber-sync:/app
    env_file:
      - docker/vault/development/.env
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db
  db:
    image: postgres:14
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    env_file:
      - docker/vault/development/.env
    ports:
      - "5432:5432"
